---
- name: Refresh-apply recovery Terraform state
  import_playbook: ../common/deploy.yml
  vars:
    terraform_stack: recovery
    terraform_operation: refresh-apply
    terraform_repository_root: "{{ playbook_dir }}/../../.."
