---
- name: Refresh-apply remote-access Terraform state
  import_playbook: ../common/deploy.yml
  vars:
    terraform_stack: remote-access
    terraform_operation: refresh-apply
    terraform_repository_root: "{{ playbook_dir }}/../../.."
