


############################################################
# Identity
############################################################
/*
module "managed_microsoft_ad" {
  source = "../../modules/managed-microsoft-ad"

  domain_name = "recovery.example.com"

  password = var.managed_ad_password

  edition = "Enterprise"

  vpc_id = module.core_recovery.vpc_id

  subnet_ids = [
    module.core_recovery.private_subnet_ids[0],
    module.core_recovery.private_subnet_ids[1]
  ]

  tags       = local.default_tags
  depends_on = [module.core_recovery]
}
*/
##################################################################################################
# Recovery
##################################################################################################

# The Recovery modules implement the AWS
# Backup architecture for the Isolated
# Recovery Environment (IRE).
#
# Together they provide backup storage,
# backup scheduling, workload selection,
# backup permissions, and immutable copies
# of recovery points for cyber recovery.

############################################
# Standard Backup Vault
############################################
# Creates the primary AWS Backup Vault used
# to store recovery points generated by
# AWS Backup jobs.
#
# Recovery points stored in this vault can
# later be copied to a Logically Air-Gapped
# Vault for ransomware protection.
module "backup_standard_vault" {

  source = "../../modules/backup-standard-vault"

  name = "ire-standard-backup-vault"

  tags = local.default_tags

}

############################################
# Logically Air-Gapped Backup Vault
############################################
# Creates an AWS Backup Logically Air-Gapped
# Vault used to store immutable copies of
# recovery points.
#
# This vault provides an additional layer of
# protection against ransomware, accidental
# deletion, and credential compromise.
module "backup_logically_air_gapped_vault" {

  source = "../../modules/backup-logically-air-gapped-vault"

  name = "ire-airgap-backup-vault"

  min_retention_days = 30

  max_retention_days = 365

  tags = local.default_tags

}

############################################
# Backup Plan
############################################

# Defines how AWS Backup protects the
# recovery environment.
#
# The Backup Plan determines when backups
# are created, how long they are retained,
# and whether recovery points are copied
# to additional Backup Vaults for
# cyber recovery.
module "backup_plan" {

  source = "../../modules/backup-plan"

  name = "ire-backup-plan"

  backup_vault_name = module.backup_standard_vault.name

  rules = {

    daily = {

      schedule = "cron(0 5 ? * * *)"

      start_window = 60

      completion_window = 180

      lifecycle = {

        cold_storage_after = 30

        delete_after = 365

      }

      copy_actions = {

        cyber_recovery = {

          destination_vault_arn = module.backup_logically_air_gapped_vault.arn

          lifecycle = {

            delete_after = 365

          }

        }

      }

    }

  }

  tags = local.default_tags

}

############################################
# Backup IAM Role
############################################

# Creates the IAM Role assumed by AWS Backup
# to perform backup and restore operations.
#
# The role includes the required trust
# relationship and managed IAM policies
# that allow AWS Backup to protect and
# recover supported AWS resources.
#
module "backup_role" {

  source = "../../modules/backup-role"

  name = "ire-backup-role"

  tags = local.default_tags

}

############################################
# Backup Selection
############################################

# Associates AWS resources with the
# Backup Plan.
#
# Only resources included in this
# selection are protected by AWS Backup.
# In this environment, the Core Recovery
# EC2 instance is designated as the
# protected workload.
module "backup_selection" {

  source = "../../modules/backup-selection"

  name = "ire-backup-selection"

  backup_plan_id = module.backup_plan.id

  iam_role_arn = module.backup_role.arn

  resources = [

    module.ec2.instance_arns["core"] # associate the core instance with the backup plan

  ]

  #tags = local.default_tags

}

##################################################################################################
# Remote Access
##################################################################################################

############################################
# Client VPN
############################################
# Provides administrator remote access into the Recovery Access VPC,
# the designated entry point for the IRE. Authorization is currently
# all-groups via certificate auth; the commented block below documents
# the planned extension point for group-scoped access once IAM Identity
# Center (SAML) is introduced as the auth source - at that point the
# interface here barely changes, it just gains an optional group
# identifier per authorization rule.add
module "client_vpn" {

  source = "../../modules/client-vpn"

  name = "ire-client-vpn"

  #server_certificate_arn     = "arn:aws:acm:us-east-1:781436988948:certificate/5bf9218b-6fbc-4cb3-a02b-0eb291d771b5"
  #root_certificate_chain_arn = "arn:aws:acm:us-east-1:781436988948:certificate/fc51c80f-aa8a-4830-ad23-5a3f42ffd26f"
  server_certificate_arn     = var.server_certificate_arn
  root_certificate_chain_arn = var.root_certificate_chain_arn

  client_cidr_block = "192.168.0.0/16"

  vpc_id = module.recovery_access.vpc_id

  network_associations = {

    az1 = {
      subnet_id = module.recovery_access.private_subnet_ids[0]
    }

    az2 = {
      subnet_id = module.recovery_access.private_subnet_ids[1]
    }

  }

  security_group_ids = [
    module.security_group.security_group_ids["management"]
  ]

  split_tunnel       = true
  transport_protocol = "udp"
  vpn_port           = 443
  dns_servers        = []

  session_timeout_hours = 8

  authorization_rules = {
    #When we  move to IAM Identity Center (SAML), your interface barely changes.  
    #you could extend the object with an optional group identifier 
    #access_group_id = "cloud-admin"
    recovery_access = {

      target_network_cidr = module.recovery_access.vpc_cidr

      authorize_all_groups = true

    }

  }

  routes = {}

}