---
- name: Apply identity-poc Terraform stack
  import_playbook: ../common/deploy.yml
  vars:
    terraform_stack: identity-poc
    terraform_operation: apply
    terraform_repository_root: "{{ playbook_dir }}/../../.."
