---
- name: Apply inspection Terraform stack
  import_playbook: ../common/deploy.yml
  vars:
    terraform_stack: inspection
    terraform_operation: apply
    terraform_repository_root: "{{ playbook_dir }}/../../.."
