---
- name: Apply persistent Terraform stack
  import_playbook: ../../terraform_deploy.yml
  vars:
    terraform_stack: persistent
    terraform_operation: apply
    terraform_repository_root: "{{ playbook_dir }}/../../.."
