##################################################################################################
# Recovery
##################################################################################################

# The Recovery modules implement the AWS
# Backup architecture for the Isolated
# Recovery Environment (IRE).
#
# Together they provide backup storage,
# backup scheduling, workload selection,
# backup permissions, and immutable copies
# of recovery points for cyber recovery.

############################################
# Standard Backup Vault
############################################
# Creates the primary AWS Backup Vault used
# to store recovery points generated by
# AWS Backup jobs.
#
# Recovery points stored in this vault can
# later be copied to a Logically Air-Gapped
# Vault for ransomware protection.
module "backup_standard_vault" {

  source = "../../modules/backup-standard-vault"

  name = "ire-standard-backup-vault"

  tags = local.default_tags

}

############################################
# Logically Air-Gapped Backup Vault
############################################
# Creates an AWS Backup Logically Air-Gapped
# Vault used to store immutable copies of
# recovery points.
#
# This vault provides an additional layer of
# protection against ransomware, accidental
# deletion, and credential compromise.
module "backup_logically_air_gapped_vault" {

  source = "../../modules/backup-logically-air-gapped-vault"

  name = "ire-airgap-backup-vault"

  min_retention_days = 30

  max_retention_days = 365

  tags = local.default_tags

}

############################################
# Backup Plan
############################################

# Defines how AWS Backup protects the
# recovery environment.
#
# The Backup Plan determines when backups
# are created, how long they are retained,
# and whether recovery points are copied
# to additional Backup Vaults for
# cyber recovery.
module "backup_plan" {

  source = "../../modules/backup-plan"

  name = "ire-backup-plan"

  backup_vault_name = module.backup_standard_vault.name

  rules = {

    daily = {

      schedule = "cron(0 5 ? * * *)"

      start_window = 60

      completion_window = 180

      lifecycle = {

        cold_storage_after = 30

        delete_after = 365

      }

      copy_actions = {

        cyber_recovery = {

          destination_vault_arn = module.backup_logically_air_gapped_vault.arn

          lifecycle = {

            delete_after = 365

          }

        }

      }

    }

  }

  tags = local.default_tags

}

############################################
# Backup IAM Role
############################################

# Creates the IAM Role assumed by AWS Backup
# to perform backup and restore operations.
#
# The role includes the required trust
# relationship and managed IAM policies
# that allow AWS Backup to protect and
# recover supported AWS resources.
#
module "backup_role" {

  source = "../../modules/backup-role"

  name = "ire-backup-role"

  tags = local.default_tags

}

############################################
# Backup Selection
############################################

# Associates AWS resources with the
# Backup Plan.
#
# Only resources included in this
# selection are protected by AWS Backup.
# In this environment, the Core Recovery
# EC2 instance is designated as the
# protected workload.
module "backup_selection" {

  source = "../../modules/backup-selection"

  name = "ire-backup-selection"

  backup_plan_id = module.backup_plan.id

  iam_role_arn = module.backup_role.arn

  resources = [

    module.ec2.instance_arns["core"] # associate the core instance with the backup plan

  ]

  tags = local.default_tags

}
