##################################################################################################
# Recovery
##################################################################################################

# The Recovery modules implement the AWS
# Backup architecture for the Isolated
# Recovery Environment (IRE).
#
# Together they provide backup storage,
# backup scheduling, workload selection,
# backup permissions, and immutable copies
# of recovery points for cyber recovery.

############################################
# Standard Backup Vault
############################################
# Creates the primary AWS Backup Vault used
# to store recovery points generated by
# AWS Backup jobs.
#
# Recovery points stored in this vault can
# later be copied to a Logically Air-Gapped
# Vault for ransomware protection.
# Purpose: Creates the standard AWS Backup vault used by the Sandbox backup plan.
# Change when: Change encryption, access policy, or deletion behavior only when backup policy changes.
module "backup_standard_vault" {

  source = "../../modules/backup-standard-vault"

  name = local.backup.standard_vault_name

  tags = local.org_tags

}

############################################
# Logically Air-Gapped Backup Vault
############################################
# Creates an AWS Backup Logically Air-Gapped
# Vault used to store immutable copies of
# recovery points.
#
# This vault provides an additional layer of
# protection against ransomware, accidental
# deletion, and credential compromise.
# Purpose: Creates the logically air-gapped AWS Backup vault used for protected backup copies.
# Change when: Change retention limits only when the approved recovery policy changes.
module "backup_logically_air_gapped_vault" {

  source = "../../modules/backup-logically-air-gapped-vault"

  name = local.backup.air_gapped_vault_name

  min_retention_days = local.backup.air_gapped_min_retention_days

  max_retention_days = local.backup.air_gapped_max_retention_days

  tags = local.org_tags

}

############################################
# Backup Plan
############################################

# Defines how AWS Backup protects the
# recovery environment.
#
# The Backup Plan determines when backups
# are created, how long they are retained,
# and whether recovery points are copied
# to additional Backup Vaults for
# cyber recovery.
# Purpose: Creates the backup schedule, lifecycle settings, and copy actions.
# Change when: Change timing or retention only when RPO and retention requirements change.
module "backup_plan" {

  source = "../../modules/backup-plan"

  name = local.backup.plan_name

  backup_vault_name = module.backup_standard_vault.name

  rules = {

    daily = {

      schedule = local.backup.plan_rules.daily.schedule

      start_window = local.backup.plan_rules.daily.start_window

      completion_window = local.backup.plan_rules.daily.completion_window

      lifecycle = {

        cold_storage_after = local.backup.plan_rules.daily.cold_storage_after

        delete_after = local.backup.plan_rules.daily.delete_after

      }

      copy_actions = {

        cyber_recovery = {

          destination_vault_arn = module.backup_logically_air_gapped_vault.arn

          lifecycle = {

            delete_after = local.backup.plan_rules.daily.cyber_recovery_delete_after

          }

        }

      }

    }

  }

  tags = local.org_tags

}

############################################
# Backup IAM Role
############################################

# Creates the IAM Role assumed by AWS Backup
# to perform backup and restore operations.
#
# The role includes the required trust
# relationship and managed IAM policies
# that allow AWS Backup to protect and
# recover supported AWS resources.
#
# Purpose: Creates the IAM role assumed by AWS Backup.
# Change when: Change permissions or trust only when protected resource types or governance requirements change.
module "backup_role" {

  source = "../../modules/backup-role"

  name = local.backup.role_name

  tags = local.org_tags

}

############################################
# Backup Selection
############################################

# Associates AWS resources with the
# Backup Plan.
#
# Only resources included in this
# selection are protected by AWS Backup.
# In this environment, the Core Recovery
# EC2 instance is designated as the
# protected workload.
# Purpose: Associates the selected Sandbox resources with the backup plan.
# Change when: Change protected resource ARNs only when backup scope changes.
module "backup_selection" {

  source = "../../modules/backup-selection"

  name = local.backup.selection_name

  backup_plan_id = module.backup_plan.id

  iam_role_arn = module.backup_role.arn

  resources = [

    module.ec2.instance_arns["core"] # associate the core instance with the backup plan

  ]

  tags = local.org_tags

}
