---
terraform_stack: identity-poc

terraform_var_files:
  - identity-poc.tfvars

terraform_environment_variable_allowlist: []

terraform_runtime_variable_allowlist:
  - vpc_id
  - subnet_ids

terraform_dependencies: {}

terraform_expected_destroy_confirmation: "DESTROY IDENTITY POC"
