---
terraform_stack: persistent

terraform_var_files:
  - common-tags.tfvars
  - persistent.tfvars

terraform_environment_variable_allowlist: []

terraform_runtime_variable_allowlist:
  - kms_key_administrators
  - client_vpn_pki_kms_key_administrators
  - client_vpn_pki_kms_key_users

terraform_dependencies: {}

terraform_expected_destroy_confirmation: "DESTROY PERSISTENT"
