---
terraform_stack: remote-access

terraform_var_files:
  - common-tags.tfvars
  - remote-access.tfvars

terraform_environment_variable_allowlist: []

terraform_runtime_variable_allowlist:
  - server_certificate_arn
  - client_root_certificate_chain_arn

terraform_dependencies:
  platform:
    - platform_contract

  identity:
    - identity_contract

terraform_expected_destroy_confirmation: "DESTROY REMOTE ACCESS"
