---
- name: Plan platform Terraform stack
  import_playbook: ../common/deploy.yml
  vars:
    terraform_stack: platform
    terraform_operation: plan
    terraform_repository_root: "{{ playbook_dir }}/../../.."
