---
- name: Plan recovery Terraform stack
  import_playbook: ../../terraform_deploy.yml
  vars:
    terraform_stack: recovery
    terraform_operation: plan
    terraform_repository_root: "{{ playbook_dir }}/../../.."
