---
- name: Plan remote-access Terraform stack
  import_playbook: ../../terraform_deploy.yml
  vars:
    terraform_stack: remote-access
    terraform_operation: plan
    terraform_repository_root: "{{ playbook_dir }}/../../.."
