---
- name: Destroy persistent Terraform stack
  import_playbook: ../common/destroy.yml
  vars:
    terraform_stack: persistent
    terraform_operation: destroy
    terraform_repository_root: "{{ playbook_dir }}/../../.."
