---
- name: Destroy platform Terraform stack
  import_playbook: ../../terraform_destroy.yml
  vars:
    terraform_stack: platform
    terraform_operation: destroy
    terraform_repository_root: "{{ playbook_dir }}/../../.."
