---
- name: Destroy recovery Terraform stack
  import_playbook: ../common/destroy.yml
  vars:
    terraform_stack: recovery
    terraform_operation: destroy
    terraform_repository_root: "{{ playbook_dir }}/../../.."
