---
# Role metadata for Galaxy/AAP; no dependent roles.
galaxy_info:
  author: IRE Platform Engineering
  description: Enterprise reusable S3 bucket role
  license: MIT

  min_ansible_version: "2.16"

dependencies: []
